# https://aka.ms/yaml
resources:
- repo: self
trigger: none
queue:
  name: Hosted VS2017
  demands: 
  - msbuild
  - visualstudio
steps:
- powershell: |
   Import-Module "$PSScriptRoot\XpandPosh\XpandPosh.ps1" 
   Publish-Module -Name XpandPosh -NugetApiKey $(PSNugetApiKey)
  displayName: 'Build'
  failOnStderr: true

