# https://aka.ms/yaml
trigger: 
  - master
queue:
  name: Hosted VS2017
  demands: 
  - msbuild
  - visualstudio
steps:
- powershell: |
   $file = "$(System.DefaultWorkingDirectory)\XpandPosh\XpandPosh.psd1"
   $data = Get-Content $file -Raw
   $manifest = Invoke-Expression $data
   $onlineVersion = (Find-Module XpandPosh -Repository PSGallery).Version.ToString()
   if ($manifest.ModuleVersion -ne $onlineVersion){
      $publish=dotnet build "$(System.DefaultWorkingDirectory)\XpandPosh\Private\Cmdlets.sln"
      if ($LASTEXITCODE){
          throw   "Fail to publish $assemblyName`r`n`r`n$publish"
      }
      $publish
      Publish-Module -Path $(System.DefaultWorkingDirectory)\XpandPosh -verbose -NugetApiKey $(PSNugetApiKey) -ErrorAction Stop    
   }
  displayName: 'Publish'
  failOnStderr: true

