# https://aka.ms/yaml
trigger: 
  - master
queue:
  name: Hosted VS2017
  demands: 
  - msbuild
  - visualstudio
steps:
- powershell: |
   Publish-Module -Path $(System.DefaultWorkingDirectory)\XpandPosh -verbose -NugetApiKey $(PSNugetApiKey) -ErrorAction Stop
  displayName: 'Publish'
  failOnStderr: true

