# https://aka.ms/yaml
resources:
- repo: self
trigger: none
queue:
  name: Hosted VS2017
  demands: 
  - msbuild
  - visualstudio
steps:
- powershell: |
   Write-output "Importing $(System.DefaultWorkingDirectory)\XpandPosh\XpandPosh.psm1"
   Get-ChildItem *.psm1 -Recurse|foreach{
      $_.FullName
      Import-Module $_.FullName -verbose
      Write-Output "Checking import"
      Get-Module XpandPosh -ListAvailable -verbose
      #Publish-Module -Name XpandPosh -NugetApiKey $(PSNugetApiKey)
   }
   
  displayName: 'Build'
  failOnStderr: true

