# https://aka.ms/yaml

trigger: 
   branches:
     include:
       - master
pool:
  vmImage: windows-2019
steps:
- checkout: self
  clean: true
- task: PowerShell@2
  inputs:
    targetType: filePath
    failOnStderr: false
    filePath: .\Build-Pipeline.ps1
    arguments: $(PSNugetApiKey)
      

